name: ci

on:
  workflow_dispatch:
    inputs:
      tModLoaderVersion:
        description: 'Version of TModLoader'     
        required: true
        default: '0.11.7.8' 
        type: string
      terrariaVersion:
        description: 'Terraria server version for TModLoader'     
        required: true
        default: '1412' 
        type: string
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          build-args:
            TMOD_VERSION=${{ github.event.inputs.tModLoaderVersion }}
            TERRARIA_VERSION=${{ github.event.inputs.terrariaVersion }}
          push: true
          tags: 
            jhbuchanan21/tmodloader:latest-github
            jhbuchanan21/tmodloader:v${{ github.event.inputs.tModLoaderVersion }}-github
